### ISSUE TITLE
Certificates created by certtool don't have new line character at end of line. This causes many errors.

### ISSUE THREAD

**Issue by r7vme** [giantswarm/certctl#56]
```
r7vme@0000fad50e971de0 ~ $ sudo cat /etc/giantswarm/g8s/ssl/etcd/etcd.pem  
-----BEGIN CERTIFICATE-----
MIIDezCCAmOgAwIBAgIUKkKMTyWtag9POaMB6UzIlVZDhpYwDQYJKoZIhvcNAQEL
....
1b7VKwUcBFMEFuDwbavFpvSOWv48MNSB6YdRh7iIclcSDPHmFA14Tn+KhR/9Tk9O
2XY7k4gWZ+TM+P/P/LURlNg+8R6QRiBSRjXoPJLwOrwtgFrZm3Ghx6t0allyRDXt
onHmCrI4bsLJ4ISYyVkHGuUg8gQis0us00MS1PO74A==
-----END CERTIFICATE-----r7vme@0000fad50e971de0 ~ $ 
```

**Comment by xh3b4sd** [comment]
Summary of our discussion. ATM `certctl`is not the problem. The problem is the difference in host cluster installation and how we secure the connection to etcd. We have to align the way we secure communication with etcd and it will just work. To fix the TLS issues with the host cluster etcd we have to put the fixes properly in place everywhere. In case the missing newlines are then still problematic we can fix it in the cert-operator as well.

**Comment by r7vme** [comment]
`certtool` causes `update-ca-certificates` to produce broken `ca-certificates.crt`

**Comment by xh3b4sd** [comment]
What do you mean with `certtool`. I cannot follow. `certctl` does not do what you describe.

**Comment by r7vme** [comment]
Yep, looks like this not a certool problem, closing.
